package dev.yashpratap.llmgateway.provider;

/**
 * A single Server-Sent Events chunk emitted during a streaming chat completion.
 *
 * @param id       unique chunk identifier (matches the parent response id)
 * @param provider the name of the downstream provider
 * @param delta    the incremental text fragment generated by the model
 * @param done     {@code true} on the final chunk indicating the stream is complete
 */
public record ChatChunk(String id, String provider, String delta, boolean done) {
}
