package dev.yashpratap.llmgateway.provider;

import java.util.List;

/**
 * Provider-agnostic chat completion response returned by the gateway.
 *
 * <p>The structure mirrors the OpenAI chat completions format so that existing
 * OpenAI-compatible clients can use the gateway without modification.</p>
 *
 * @param id          unique response identifier generated by the provider
 * @param model       the model that generated the response
 * @param provider    the name of the downstream provider
 * @param choices     one or more completion choices
 * @param usage       token usage and cost breakdown
 * @param gatewayMeta gateway-level metadata (provider, cache hit, latency)
 */
public record ChatResponse(
        String id,
        String model,
        String provider,
        List<Choice> choices,
        Usage usage,
        GatewayMeta gatewayMeta) {
}
