package dev.yashpratap.llmgateway.provider;

/**
 * A single completion choice returned by the provider.
 *
 * @param index        zero-based index of this choice in the response
 * @param message      the assistant message generated by the model
 * @param finishReason the reason the model stopped generating (e.g. {@code stop}, {@code length})
 */
public record Choice(int index, Message message, String finishReason) {
}
