package dev.yashpratap.llmgateway.domain;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * JPA entity representing a tenant (customer) of the LLM Gateway.
 *
 * <p>Each tenant has an associated plan that governs rate limits and budget caps.
 * All API keys, budgets, and routing policies are owned by a tenant.</p>
 */
@Entity
@Table(name = "tenants")
@Getter
@Setter
@NoArgsConstructor
public class Tenant {

    /** Surrogate primary key, generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Human-readable unique name for the tenant. */
    @Column(nullable = false, unique = true)
    private String name;

    /** Subscription plan (e.g. FREE, PRO, ENTERPRISE). */
    @Column(nullable = false)
    private String plan;

    /** Timestamp when the tenant record was created. */
    @Column(nullable = false)
    private LocalDateTime createdAt;

    /** Timestamp of the most recent update to this record. */
    @Column(nullable = false)
    private LocalDateTime updatedAt;

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }
}
